### ISSUE TITLE
Add payment ID to send screen

### ISSUE THREAD

**Issue by CaptainMeatloaf** [turtlecoin/turtle-wallet#16]
Some exchanges require may require a payment ID to be specified for you to deposit TRTL to them, so an optional field needs to be added.

Bear in mind this wallet is supposed to be user friendly, so it would perhaps be prudent to hide the payment ID behind a button saying "Need to give a payment ID too?" or something of the sort.

**Comment by paulie-g** [comment]
+1000, fwiw. The number one use for a trtl wallet at this point is a place to mine to, since tradeogre requires a payment id and the pools currently don't support it. It then inevitably follows that you need to be able to send to tradeogre (or another exchange that might start trading trtl) and you can't very well do it without a payment id.

**Comment by ftwillms** [comment]
https://github.com/turtlecoin/turtle-wallet/pull/32 in the works

**Comment by paulie-g** [comment]
@ftwillms I applied that pr locally, the conflict doesn't break anything substantive - it's just a couple glade positioning values. By 'in the works', do you mean that someone is working to merge that pr into head or that someone needs to do that work?

**Comment by CaptainMeatloaf** [comment]
It means the requester needs to rebase the commit, and make sure the glade positioning is correct.

I know this is a popular feature, so if the original requester doesn't reappear in the next day or so, you could finish their work and make a pull request yourself.

**Comment by CaptainMeatloaf** [comment]
Complete in #32
